### ISSUE TITLE
Ensure dimension coordinates are not chunked?

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-forge/pangeo-forge-recipes#209]
I'm not sure if this is specific to the [gridMET feedstock](https://github.com/pangeo-forge/gridmet-feedstock), but posting here for visibility anyway.

The variables in gridMET have dimensions `(time, lon, lat)`, and are chunked by `(time,)`. Currently, opening the Zarr store is quite slow: From outside Azure (requires adlfs to be installed)

```python
In [1]: import fsspec, xarray as xr

In [2]: store = fsspec.get_mapper("abfs://gridmet/gridmet.zarr", account_name="ai4edataeuwest")

In [3]: %time ds = xr.open_zarr(store, consolidated=True)
CPU times: user 6.9 s, sys: 624 ms, total: 7.52 s
Wall time: 2min 34s
```

I *think* this is because the array for one of the coordinates, `time`, is chunked:

```python
In [5]: g = zarr.open_consolidated(store)

In [6]: %time g = zarr.open_consolidated(store)
CPU times: user 15.6 ms, sys: 0 ns, total: 15.6 ms
Wall time: 263 ms

In [7]: print(g.time.info)
Name               : /time
Type               : zarr.core.Array
Data type          : int64
Shape              : (15341,)
Chunk shape        : (30,)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.ConsolidatedMetadataStore
Chunk store type   : fsspec.mapping.FSMap
No. bytes          : 122728 (119.9K)
Chunks initialized : 512/512
```

So a few questions:

1. Does pangeo-forge want to ensure that coordinates arrays are not chunked? At least by default, I think not chunking makes sense, because xarray eagerly loads them into memory.
2. Is this an issue in pangeo-forge-recipes itself, or in how gridMET is using it?

cc @sharkinsspatial

**Comment by rabernat** [comment]
There are two issues here:

1. If fsspec async magic is working properly, it should definitely not take 2 minutes to read 512 chunks. This suggests an issue with adlfs. I am nearly certain that s3fs and gcsfs are not nearly so slow on this. Does adlfs mapper implement `getitems`?
2. YES, we should be rechunking these coordinates. This was also discussed in https://github.com/pangeo-forge/pangeo-forge-recipes/pull/86#issuecomment-811501781 and https://github.com/pangeo-forge/pangeo-forge-recipes/issues/90. My preference would be to do it inside `finalize_target`, the same place we consolidate the metadata. Since the data are small we don't need rechunker or anything fancy, we just load the coordinate into memory and make a new array with a contiguous chunk. PR would be very welcome here.

**Comment by TomAugspurger** [comment]
Cool, thanks. I'll look into consolidating / rewriting the coordinates arrays in `finalize_target`.
