### ISSUE TITLE
Existing `to_beam` compiler throws `NameError`s on Dataflow

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/pangeo-forge-recipes#384]
While the beam refactor [continues](https://github.com/pangeo-forge/pangeo-forge-recipes/pulls?q=is%3Apr+label%3A%22beam+refactor%22+), the existing `to_beam` compiler has proven useful as an alternative deployment option, especially when we've hit difficult-to-resolve memory issues in Prefect; e.g. https://github.com/pangeo-forge/gpcp-feedstock/issues/4.

As documented in https://github.com/pangeo-forge/staged-recipes/pull/151#issuecomment-1184747564 (and following comments), the existing `to_beam` compiler exhibits some confusing serialization issues when run on Dataflow. Specifically, `NameError`s are thrown by global names used within function scopes, even with the `save_main_session=True` option set, as recommended in

> https://cloud.google.com/dataflow/docs/resources/faq#how_do_i_handle_nameerrors

Strangely, the specific `NameError` we're seeing in the linked PR is thrown by the builtin `list` function, which should be available in any Python session. As a next step towards debugging this, I'm going to look into options for local reproducibility. These errors do not occur with the `DirectRunner`, but perhaps there is another way to reproduce them locally, which would be of great benefit to debugging.

**Comment by cisaacstern** [comment]
In addition to the `to_beam` compiler itself, it is possible that our particular job registration config may also be affecting and/or causing this issue. That config lives [here](https://github.com/pangeo-forge/registrar/blob/e4af236e793d28e203244858ab09c515b8537140/registrar/register_job.py#L140-L160), and for those without access to the private repo:

```python
    beam_options = PipelineOptions(
        runner="DataflowRunner",
        project=os.environ["PROJECT_NAME"],
        service_account_email="pangeo-forge-dataflow@pangeo-forge-4967.iam.gserviceaccount.com",
        job_name=job_name,
        # TODO: Update temp bucket name once we move out of 'test' phase.
        temp_location="gs://beam-dataflow-test/temp",
        # Our institutional GCP policies forbid public IPs.
        use_public_ips=False,
        # The private network we've already set up is in us-central1, so that's our only option
        # unless/until we create other private networks elsewhere. See:
        #   - https://github.com/pangeo-forge/pangeo-forge-gcs-bakery/pull/30
        #   - https://console.cloud.google.com/networking/networks/details/
        #     default?project=pangeo-forge-4967&pageTab=SUBNETS
        region="us-central1",
        # https://cloud.google.com/dataflow/docs/guides/using-custom-containers#usage
        experiments=["use_runner_v2"],
        sdk_container_image=f"docker.io/{CONTAINER_REGISTRY_REPO}:{pangeo_forge_version}",
        # https://cloud.google.com/dataflow/docs/resources/faq#how_do_i_handle_nameerrors
        save_main_session=True,
    )
```
Among other things, perhaps the use of a custom container is related to this issue. 🤷

**Comment by cisaacstern** [comment]
Thanks for looping in others with expertise in this area, Alex.

David, we'll be grateful for any insight. Please let me know if I can clarify the question further. For your reference, [here's the `to_beam` code](https://github.com/pangeo-forge/pangeo-forge-recipes/blob/master/pangeo_forge_recipes/executors/beam.py) referenced above, which defines our transforms.

And yes, would love to get together next week to work on this, Alex 😄

**Comment by davidcavazos** [comment]
That's hard to know with only this information. As you said, `list` should be available from the standard library. In my past experience, these kinds of errors are due to some pickling error of the main session. When something fails to pickle (usually some module or object with some unserializable state), I've had cases when the entire pipeline fails as expected, but I've also had cases where it simply "silently" ignores the error and keeps going with an empty main session. I'm not sure if it's dependent on the Beam version or of the Dataflow setup. But in the end it works as if we had `save_main_session=False`. I've had to dig into the workers' logs and see the container/boot/system logs to find that out.

The fix is usually doing the "unpicklable" stuff inside the functions rather than in the global scope, like importing "unpickleable" modules inside the functions rather than globally. It's almost as if we weren't saving the main session, so it's a little annoying, but at least it won't make the main session crash and you'll have access to your functions and other standard library stuff.

It's been a while, but I think I've had these kinds of errors when importing `aiplatform` and `ee`, so they might be keeping some non-trivial global mutable state. At least I know `ee` does for initialization and authentication.

I hope that helps.

**Comment by cisaacstern** [comment]
Thanks so much for weighing in, David. This problem was indeed related to pickling. At the Beam Summit, @kerrydc pointed me to the pipeline option

```python
pickle_library="cloudpickle"
```
which solved this problem. This option, as far as we can tell, is only referenced in https://beam.apache.org/blog/beam-2.36.0/, but Kerry is aware of that and has it on his radar to make this option more visible.

Thanks to all for your insights here, going to close this since the issue is solved!

**Comment by derekocallaghan** [comment]
FYI there's an existing issue in Beam where the specified `pickle_library` isn't used when the `pipeline.run()` session is dumped with `save_main_session` (this is the problem I mentioned in yesterday's Pangeo Forge call). I've been using a local workaround to ensure `cloudpickle` is used instead of the default `dill`:

https://github.com/apache/beam/issues/21615#issuecomment-1290436909

The specified library is used later on in Beam (e.g. https://github.com/apache/beam/blob/master/sdks/python/apache_beam/runners/worker/sdk_worker_main.py#L102), I think the issue is only with `save_main_session`.

**Comment by davidcavazos** [comment]
This looks like something that would benefit the Beam SDK itself. Do you have plans on making a commit to Beam to allow save_main_session work as expected with the cloudpickle? Thanks for looking into it.

**Comment by derekocallaghan** [comment]
Hi @davidcavazos, when I was looking through the Beam code I think I noticed other situations where the default library was used without at least one call to `set_library()`, but I'd have to double-check to confirm. For the moment, I just added the call locally prior to the `save_main_session` dump. I could look into putting together a PR, probably in the next couple of weeks if that suits.

**Comment by derekocallaghan** [comment]
> Hi @davidcavazos, when I was looking through the Beam code I think I noticed other situations where the default library was used without at least one call to `set_library()`, but I'd have to double-check to confirm. For the moment, I just added the call locally prior to the `save_main_session` dump. I could look into putting together a PR, probably in the next couple of weeks if that suits.

It looks like this is fixed in Beam now: https://github.com/apache/beam/pull/24069
