### ISSUE TITLE
add GRIB2ReferenceRecipe 

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-forge/pangeo-forge-recipes#387]
We have `HDFReferenceRecipe`, but kerchunk also handles GRIB2.    Perhaps `GRIB2ReferenceRecipe`?

**Comment by darothen** [comment]
This seems pretty useful; I've been playing around with this during the evening, and it looks like fsspec/kerchunk#198 would unblock writing recipes that read from remotely hosted GRIB files. Directly translating the example HRRR concatenation into a recipe here would be a really cool addition. Happy to play around with this and propose a refactor for `HDFReferenceRecipe` once that upstream PR in kerchunk lands.

**Comment by darothen** [comment]
A quick update - I was able to hack out a minimal working example of using the existing `HDFReferenceRecipe` class to read GRIB2 files. The demo code is in #390, but note that it would help if you build a very recent version of kerchunk - at least after the significant GRIB utility refactor in fsspec/kerchunk#198, and for the demo code below, fsspec/kerchunk#204.

In a nut-shell, it was pretty straightforward to modify the existing codepaths for scanning GRIB files. A major departure from the HDF formulation is that each GRIB message gets its own reference, so we need a more elegant way to combine this so that a single GRIB file maps to a single Zarr file. I opted just to flatten all the messages, assuming metadata about coords remains constant, but there are other places this could be fixed, namely in the `MultiZarrToZarr` utility. I think a simple dataclass which helps mediate between the reference spec produced by `fsspec` would help here, since there will probably be a variety of reference lists that need to be handled.

The other big change would be the actual interface for `HDFReferenceRecipe` - or whatever it would become. Given the small inconsistencies between the NetCDF4 reader and the GRIB reader here, a really good case could be made for having separate reference classes, but I'll explore how much overlap there is and see if there is a sensible re-factoring that would allow easy extension for each specialized filetype.

For a quick demo, here's a [simple gist](https://gist.github.com/darothen/5380e223ae5bc894006a5b6ed5a27cbb) which subsets from a HRRR forecast and concatenates the output. This workflow is **vastly superior** to most ones that I've seen for extracting useful data from the online HRRR archive - it's fast, easy to modify, and is very concise thanks to the great mechanics inside pangeo-forge.

**Comment by darothen** [comment]
Another quick update - I started re-factoring a generic `ReferenceRecipe` so that the custom code for each file format could be added in. In general things "just work", but debugging an issue with s3 paths not being read properly. Will consolidate the re-factor and update tests before asking for reviews on the PR.

**Comment by rabernat** [comment]
Thanks for working on this @darothen!

For reference, we are in the process of completely refactoring the internals of pangeo forge recipes. (See #376 and #391 for latest progress.) That is happening on the `beam_refactor` branch. So just keep that in mind before choosing to spend a lot of time on refactoring the current code base.

That said, I'm :+1: on doing whatever is necessary to make Grib work with the current code.

**Comment by darothen** [comment]
No worries @rabernat. This project is really just an excuse for me to get much more comfortable with the internals of `fsspec` / `kerchunk`. I don't think this work will result in much more than a simple re-factor - but happy to contribute something bigger when the larger library re-factors are complete!

**Comment by cisaacstern** [comment]
Resolved by #486.

See [this file](https://github.com/pangeo-forge/pangeo-forge-recipes/blob/beam-refactor/tests-integration/test_hrrr_kerchunk_concat_step.py) for the merged version of the integration test mentioned in previous comment.

Here's an excerpt demonstrating the GRIB2 -> kerchunk pipeline there:

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/97a7b3c211263ada4d0d73770027af782f58e8af/tests-integration/test_hrrr_kerchunk_concat_step.py#L52-L66

As mentioned elsewhere, would love feedback on this from anyone working with GRIB2, in the form of issues, bug reports, etc.

**Comment by darothen** [comment]
Hey @cisaacstern thanks for the awesome update here! It sounds like the solution you landed on is a great path forward.

I'll try to test-drive this with one of my personal data processing pipelines. Not sure when I'll find the time, but we will try to ping back here with results if I can squeeze in the work some evening this week.
